// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBL7eyMSCcGPJf6k2gA8QtEJJl93bMhE',
    appId: '1:684501001780:web:6188118df971cd91da0c61',
    messagingSenderId: '684501001780',
    projectId: 're-memories',
    authDomain: 're-memories.firebaseapp.com',
    storageBucket: 're-memories.appspot.com',
    measurementId: 'G-Z1RVL3TLL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXBgVEVuiVXbFEdLg5pOZntTGD9SuR92E',
    appId: '1:684501001780:android:c91f2f75b16a2e63da0c61',
    messagingSenderId: '684501001780',
    projectId: 're-memories',
    storageBucket: 're-memories.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAndkcYqwnGu8lsMYWsh2dAd5Jme2corQk',
    appId: '1:684501001780:ios:e2873272064e6aa2da0c61',
    messagingSenderId: '684501001780',
    projectId: 're-memories',
    storageBucket: 're-memories.appspot.com',
    androidClientId: '684501001780-mm5v8c7ppm1077qvt4koipj6n7i63b6o.apps.googleusercontent.com',
    iosClientId: '684501001780-t4ijarchfrt1tpld5m88pitou81iv6qv.apps.googleusercontent.com',
    iosBundleId: 'id.rememories.remorable',
  );
}
